!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist
!includeurl AWSPUML/common.puml
!includeurl AWSPUML/Storage/AmazonS3/AmazonS3.puml
!includeurl AWSPUML/Storage/AmazonS3/bucket/bucket.puml
!includeurl AWSPUML/Messaging/AmazonSES/AmazonSES.puml
!includeurl AWSPUML/NetworkingContentDelivery/AmazonRoute53/AmazonRoute53.puml
!includeurl AWSPUML/NetworkingContentDelivery/AmazonVPC/AmazonVPC.puml
!includeurl AWSPUML/NetworkingContentDelivery/AmazonCloudFront/AmazonCloudFront.puml
!includeurl AWSPUML/Compute/AmazonEC2/AmazonEC2.puml
!includeurl AWSPUML/NetworkingContentDelivery/AmazonRoute53/AmazonRoute53.puml
!includeurl AWSPUML/General/AWScloud/AWScloud.puml
!includeurl AWSPUML/General/client/client.puml
!includeurl AWSPUML/General/user/user.puml
!includeurl AWSPUML/Database/AmazonDynamoDB/AmazonDynamoDB.puml
!includeurl AWSPUML/General/traditionalserver/traditionalserver.puml

@startuml

USER(user)
CLIENT(browser)

AWSCLOUD(aws) {

    AMAZONROUTE53(route_53)

    AMAZONCLOUDFRONT(cloud_front, "Front End CDN")

    AMAZONS3(s3) {
        BUCKET(artifacts, "Front End Artifacts and Email Storage")
    }


    AMAZONVPC(vpc){
        AMAZONEC2(ec2, "Back End Server, Database and Bitcoin Node")
    }

    AMAZONSES(ses)

    AMAZONDYNAMODB(dynamo, "Secret Storage")

}

TRADITIONALSERVER(infura, "Ethereum Node")

user - browser

browser - route_53

route_53 -d-> cloud_front
route_53 -d-> ec2

cloud_front -d-> artifacts

ec2 -d-> ses
ec2 -d-> dynamo

ses -d-> artifacts

ec2 -d-> infura

@enduml